config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'privacy', to: 'home#privacy'
  get 'terms', to: 'home#terms'
  get '/auth/:provider/callback' => 'sessions#omniauth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.user_name = auth.info.name
      user.email = auth.info.email
      user.image = auth.info.image
      user.password = SecureRandom.hex
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :authenticate_user!

  def authenticate_user!
    unless current_user
      redirect_to login_path, notice: 'Please login'
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def privacy
  end

  def terms
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!

  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'You are logged in.'
    else
      flash.now[:alert] = 'Your email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You are logged out!'
  end

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to root_url, notice: 'You are logged in.'
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:new, :create]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if current_user %>
  <p>Logged in as <%= current_user.email %>.</p>

  <h2>User Details</h2>
  <% if current_user.user_name %>
    <p>Name <%= current_user.user_name %>.</p>
  <% end %>

  <% if current_user.image %>
    <%= image_tag current_user.image %>
  <% end %>

  <br/>
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Log In", login_path %> or
  <%= link_to "Sign Up", signup_path %>

<% end %>
<p><%= notice %></p>

app/views/home/privacy.html.erb
Who we are, and what is this?

We're Picfair, a company that wants to help photographers make money from their creativity. Our offices are at 154-158 Shoreditch High St, London E1 6HU, and our registered company address is 2 Underwood Row, London, N1 7LQ -

This Privacy Policy is our way to try to explain as clearly as possible exactly how we use and collect your data. We've tried to explain and collate as much as possible, but if there's anything we need to add or amend, we reserve the right to make changes to it, without giving you notice, whenever we need to. But it will always be here, on our website, if you ever want to check for updates.

Importantly, if you ever wish to request any personal information we hold on you, you can do that whenever you like, by emailing datarequest@picfair.com or you can always contact us about anything, using our support form.

Collection of personal information

1. BROWSING PICFAIR AND USER STORES

You can browse millions of beautiful images from across the globe on Picfair, and on user stores without logging in or submitting any personal information.

We use a number of analytic products to track visitor behaviour on our, and our users’ sites, because we're always trying to make Picfair as useful as possible. This means we monitor things like clicks, your Internet Protocol (IP) address, browser types, CPU speed, site performance, operating systems and device types, time spent on pages, time and time zone, the page that referred you to us, Internet Service Providers, and pages viewed. We use this information to analyse trends and improve site functionality on an individual and aggregate basis.

These analytic services rely on software such as cookies. Cookies are small, unique text files that a website sends to your computer when you visit a site and do things on it. You can read more about Cookies and how they’re employed on Picfair and users’ stores in our Cookie Policy.

2. USING PICFAIR AND USER STORES AS A PHOTOGRAPHER, IMAGE BUYER OR PRINT BUYER.

a. Social sign in

You can sign up to Picfair using Facebook and Twitter - this uses some information that these services already have in order to speed up your sign up process (and so that you can log in with a single click via these services in the future). This includes your first name, last name, and email address.

b. Profile information

Whether you are a photographer, an image buyer, or a print customer, once you are signed up to Picfair you may be asked for any of the following information:

Contact information such as your name, email address, and phone number
Billing information such as your credit or debit card number, expiration date, and billing address
Profile information such as your username, password, location, job title, photography specialisations and qualifications, company name, social media accounts, VAT number, profile bio
Delivery information - your postal address
Payout methods including paypal addresses, and British bank account sort codes and account numbers
In order to reduce errors and to authenticate our users and clients, we may from time to time use publicly accessible third-party sources to supplement the information you give us in order ensure the veracity of our records.

c. Uploading images

When you upload images to Picfair, we ask you to add a title, caption, tags and price. We also analyse the image file itself for any technical or descriptive information - this may be in the format of EXIF, IPTC or other data protocols. Please note that this information will be stored by Picfair, and may be viewable by image customers and our distribution partners.

Changing & requesting your information

Your profile information is always accessible and editable in the "Dashboard' section of your account. Information relating to orders, cashouts, and deliveries are stored on our databases to ensure that we can reference any such orders, cashouts or deliveries should a problem arise.

As with everything relating to your privacy on Picfair, you can request to view any information we have stored by emailing datarequest@picfair.com.

Storing your information

Information gathered as described in b. and c. above are stored as followed:

Your profile information, contact information, delivery information, billing information and payout request information are stored in our core database on Heroku.
Your images, including all of their metadata, are stored on Cloudinary, with a backup copy on AWS
Your contact information is stored by Sendgrid, Mailchimp, and Active Campaign so that we can get in contact with you
Protecting your personal information

The information you provide to Picfair is protected as follows:

The Personal Information that you provide in connection with the use of the Site is protected in several ways.

Access by you to your account profile is available through a password and unique customer ID / email selected by you. This password is encrypted. You should strive to use a strong, alpha-numeric password which you should not divulge to anyone or reuse on other websites.

Your Personal Information resides with databases run by Heroku who have a comprehensive security policy: www.heroku.com/policy/security. Your Personal Information is encrypted whenever it is transmitted to Picfair. We do not store your payment card details, although our payment provider (Stripe) may store them if you choose.

We strive to protect the Personal Information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we take into account the sensitivity of the Personal Information we collect, process and store, and the current state of technology to use these measures protect your Personal Information, we cannot guarantee its absolute security.

If you have any questions about security on our Web Sites contact us

How we use your personal information

Picfair collects your information in order to comply with our legal obligations, to provide you with products, and to improve our service to you. We do not sell or seek to make money from your personally identifiable information. Here are the way we use your information:

To confirm product purchases and deliver invoices and receipts
To confirm that cashout requests have been processed
To notify you of, and confirm, actions you have taken on the site
To alert you to significant changes on the website
To alert you to significant changes to the company
To confirm image licence allocation and notify of image purchases and rewards
To alert you to any website or company changes that require your attention
To keep you informed about special offers and services
To investigate any alleged breaches of our Contributors Agreements, Licence Agreements, or general terms of service
To customise your experience of our website, including targeting offerings and services to you
To meet our service development needs and in improving the performance of the website
To welcome you to the site and confirm your account
To allow you to opt in or opt out of marketing correspondence
To respond to your customer service queries
Data Retention

Information collected by Picfair will be stored for as long as you hold an account. If you wish to delete your account please visit your Account Dashboard or contact us. When an account deletion request is received, we will delete/anonymise your account, excluding transaction information (i.e. sales & purchases).

Advertising Activities

Information collected from users help us create interesting and tailor-made advertising for you elsewhere on the web. Picfair collects information in a pseudonymised way - including information on your computer and Internet access, operating system as well as platform, date and time of your visit or products viewed.This is done using cookies stored on your computer that make identifying a pseudonymised user possible without any reference to your personal data.You can read more about Cookies and how they’re employed on Picfair and users’ stores in our Cookie Policy.

3rd Parties

Picfair does not use any 3rd party services that collect your information that do not perform core functionalities of our website or products. The 3rd Parties we use that are not already referenced in this Privacy Policy are as follows:

Stripe: This is our payment processing company
Cloudflare - This is a website wrapper that protects against cyber attacks
Zendesk - This helps us gather and process customer queries
BrickFTP - this helps us ingest and process large collections of images and their metadata
Links to 3rd Party Sites

Our site includes many links to 3rd party sites, including the personal websites of many of our photographers. If you submit any personal information to these sites, your information is not protected by this Privacy Policy.

Opting Out

You can opt out of any Picfair newsletters by clicking on the "email preferences" section of your account, or by clicking on the "unsubscribe" options contained within any newsletters that you recieve. This will not opt you out of any non-promotional emails that Picfair sends you, such as, but not limited to, changes to our Privacy Policy, General Terms, Contributor Agreements, Licence Agreements, service-related announcements, emails triggered by actions on the site, registration emails, notifications relating to significant changes to core Picfair products or services, and any of the other legitimate interests listed above. If you wish to not receive any of these emails, you can choose to delete your account via your Account Dashboard, or you can contact us.

app/views/home/terms.html.erb
A Terms of Service agreement can be used for any kind of website or mobile app, from iOS or Android apps to SaaS apps, ecommerce websites and blogs.

That's because it provides huge benefits for a range of businesses.

1.
FAQ: Terms of Service
2.
How to Enforce Your Terms of Service
3.
Download Terms of Service Template
Haivng this agreement helps you set out the rules and guidelines that your users or visitors must agree to in order to use your website or app such as:

Not stealing your content and violating copyright laws
Not spamming other users
Not using your site for illegal activities
These agreements are commonly abbreviated as ToS and are also referred to as a Terms and Conditions agreement, Conditions of Use, or User Agreement.

Regardless of what you call your Terms of Service, the aim of the agreement is the same:

Disclose the rules and restrictions that your users must adhere to
Maintain your right to terminate abusive accounts
Make your copyright, trademark and intellectual property rights known
Limit your liability
Disclaim warranties

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoogleOauth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="google-signin-client_id" content="930432434977-ugm0oqsp81du5d1rs9or8mvb1grmmi85.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
<%= link_to "Sign Up with Google", '/auth/google_oauth2' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>